
const String uyelikSozlesmesiContent = '''

Üyelik Sözleşmesi 
Güncelleme Tarihi: 04.08.2025

1. TARAFLAR
İşbu Üyelik Sözleşmesi ("Sözleşme"); https://www.optiyou.com.tr/ ve mobil cihaz uygulamalarının sahibi olan ve 15 Temmuz Mah. Bahar Cad. No:61 Bağcılar/İstanbul adresinde bulunan  Optiyou Shoes Ortopedi Sanayi ve. A.Ş.  ( “Optiyou Shoes” ) ile; https://www.optiyou.com.tr/ ve mobil uygulamasına (“Platform”) aşağıdaki şartları kabul ederek üye olan websitesi kullanıcısı veya mobil cihazlara kurulan uygulamalardan üye olan kullanıcı ( “Üye” ) arasında, Üye'nin Optiyou Shoes’un sunduğu Hizmetler'den yararlanmasına ilişkin koşulların belirlenmesi için akdedilmiştir.
Optiyou Shoes ve Üye işbu Üyelik Sözleşmesi'nde ayrı ayrı “Taraf” birlikte “Taraflar” olarak anılacaklardır.
TANIMLAR
Alıcı : Platform’dan ürün ve/veya hizmet satın alan gerçek ve/veya tüzel kişileri ifade eder.
Gizlilik Politikası ve Veri Koruma Bildirimi : Üyeler’in Platform üzerinden ilettikleri kişisel verilerin, Optiyou Shoes tarafından hangi amaçlarla ve ne şekilde kullanılacağı gibi konular da dahil olmak üzere Optiyou Shoes kişisel verilere ve çerez kullanımına ilişkin genel gizlilik politikasını düzenleyen ve Platform üzerinden https://www.optiyou.com.tr/english-privacy-policy linkinden erişilebilecek olan metni ifade eder.
Hesabım Sayfası : Üye’nin Platform’da yer alan çeşitli uygulamalardan ve Hizmetler’den yararlanabilmesi için gerekli işlemleri gerçekleştirebildiği, kişisel bilgilerini ve uygulama bazında kendisinden talep edilen bilgilerini girdiği sadece ilgili Üye tarafından belirlenen kullanıcı adı ve şifre ile erişilebilen Üye’ye özel sayfayı ifade eder.
Hizmetler : Üyeler’in işbu Üyelik Sözleşmesi içerisinde tanımlı olan iş ve işlemlerini gerçekleştirmelerini sağlamak amacıyla Optiyou Shoes tarafından ortaya konulan uygulamaları ifade eder.
TARAFLARIN HAK VE YÜKÜMLÜLÜKLERİ
3.1. Üyelik statüsünün kazanılması için, Üye olmak isteyen kullanıcının, Platform’da bulunan işbu Üyelik Sözleşmesi'ni onaylayarak, burada talep edilen bilgileri doğru ve güncel bilgilerle doldurması gerekmektedir. Üye olmak isteyen kullanıcının 18 (on sekiz) yaşını doldurmuş olması aranacaktır. Söz konusu Üyelik Sözleşmesi’ni doldururken doğru ve güncel bilgi sağlamayan Üye, bu sebeple doğabilecek tüm zararlardan bizzat sorumludur. Üye, Üyelik statüsünü Hesabım Sayfası'ndan ulaşabileceği "Üyelik İptali" butonuna basarak her zaman sonlandırabilme hakkına sahiptir
3.2. Üyelik hak ve yükümlülüklerinin hangi kişiye ait olduğu konusunda ihtilaf bulunması ve bu hususta söz konusu kişilerin Optiyou Shoes’tan talepte bulunması halinde, ilgili Üyelik hesabı kullanılarak herhangi bir Hizmet için Optiyou Shoes’a ödeme yapan en son kişinin Üyelik hesabının sahibi olduğunu kabul ederek, bu doğrultuda işlem yapacaktır.
3.3. Üye, Platform üzerinde gerçekleştirdiği işlemlerde ve yazışmalarda, işbu Üyelik Sözleşmesi'nin hükümlerine, Platform’da belirtilen tüm koşullara, yürürlükteki mevzuata ve ahlak kurallarına uygun olarak hareket edeceğini kabul ettiğini beyan eder. Üye'nin Platform dâhilinde yaptığı işlem ve eylemlere ilişkin hukuki ve cezai sorumluluk kendisine aittir.
3.4. Optiyou Shoes, yürürlükteki mevzuat uyarınca yetkili makamların talebi halinde, Üye'nin kendisinde bulunan bilgilerini söz konusu makamlarla paylaşabilecektir.
3.5. Üye'nin Hesabım Sayfası'na erişmek ve Platform üzerinden işlem gerçekleştirebilmek için ihtiyaç duyduğu kullanıcı adı ve şifre bilgisi, Üye tarafından oluşturulmakta olup, söz konusu bilgilerin güvenliği ve gizliliği tamamen Üye'nin sorumluluğundadır. Üye, kendisine ait kullanıcı adı ve şifre ile gerçekleştirilen işlemlerin kendisi tarafından gerçekleştirilmiş olduğunu, bu işlemlerden kaynaklanan sorumluluğunun peşinen kendisine ait olduğunu, bu şekilde gerçekleştirilen iş ve işlemleri kendisinin gerçekleştirmediği yolunda herhangi bir def'i ve/veya itiraz ileri süremeyeceğini ve/veya bu def'i veya itiraza dayanarak yükümlülüklerini yerine getirmekten kaçınmayacağını kabul, beyan ve taahhüt eder.
3.6. Üye, Platform’u aşağıda sayılan haller başta olmak üzere hukuka ve ahlaka aykırı bir şekilde kullanmayacaktır.
Platform’un herhangi bir kişi adına veri tabanı, kayıt veya rehber yaratmak, kontrol etmek, güncellemek veya değiştirmek amacıyla kullanılması;
Platform’un bütününün veya bir bölümünün bozma, değiştirme veya ters mühendislik yapma amacıyla kullanılması;
Yanlış bilgiler veya başka bir kişinin bilgileri kullanılarak işlem yapılması, yanlış veya yanıltıcı ikametgâh adresi, elektronik posta adresi, iletişim, ödeme veya hesap bilgileri de dahil yanlış veya yanıltıcı kişisel veriler kullanmak suretiyle gerçek olmayan Üyelik hesapları oluşturulması ve bu hesapların Üyelik Sözleşmesi'ne veya yürürlükte mevzuata aykırı şekilde kullanılması, başka bir Üye'nin hesabının izinsiz kullanılması, başka birinin yerine geçilerek ya da yanlış bir isimle işlemlere taraf ya da katılımcı olunması;
Yorum ve puanlama sistemlerinin; Platform’daki yorumları Platform dışında yayınlamak gibi Platform dışı amaçlar için kullanılması veya sistemleri manipüle edecek şekilde kullanılma amaçları dışında kullanılması;
Virüs veya Platform’a, Platform’un veri tabanına, Platform üzerinde yer alan herhangi bir içeriğe zarar verici herhangi başka bir teknoloji yayılması;
Platform tarafından belirlenmiş olan iletişimler ve teknik sistemler üzerinde makul olmayan veya orantısız derecede büyük yüklemeler yaratacak ya da teknik işleyişe zarar verecek faaliyetlerde bulunulması, Optiyou Shoes’un önceden yazılı iznini alınmaksızın Platform’un üzerinde otomatik program, robot, web crawler, örümcek, veri madenciliği (data mining) ve veri taraması (data crawling) gibi "screen scraping" yazılımları veya sistemleri kullanılması ve bu şekilde Platform’da yer alan herhangi bir içeriğin tamamının veya bir kısmının izinsiz kopyalanarak, yayınlanması veya kullanılması.
3.7. Üye, Platform’da yaptığı işlemleri Optiyou Shoes’a maddi ve Platform’a teknik olarak hiçbir surette zarar vermeyecek şekilde yürütmekle yükümlüdür. Üye, Platform’a zarar verecek her türlü program, virüs, yazılım, lisansız ürün, truva atı vb. içermemesi için gerekli koruyucu yazılımları ve lisanslı ürünleri kullanmak da dâhil olmak üzere gerekli her türlü tedbiri aldığını kabul ve taahhüt eder. Üye ayrıca Hesap Sayfası'na robot veya otomatik giriş yöntemleriyle girmeyeceğini kabul eder.
3.8. Platform’un veya üzerindeki içeriğin işbu Üyelik Sözleşmesi ile belirlenen kullanım şartlarına veya yürürlükteki mevzuat hükümlerine aykırı olarak kullanılması hukuka aykırı olup; KİFİDİS’in ilgili talep, dava ve takip hakları saklıdır.
GİZLİLİK
4.1. Optiyou Shoes, Üye'nin Platform’da sunulan Hizmetler'den yararlanabilmek için Platform üzerinden kendisine sağladığı kişisel verilerin 6698 sayılı Kişisel Verilerin Korunması Kanunu da dahil her türlü mevzuata uygun bir şekilde işlenmesine, güvenliğinin sağlanmasına ve korunmasına önem vermektedir. Optiyou Shoes, bu kapsamda Üye'nin sağladığı kişisel veriler https://www.optiyou.com.tr/english-privacy-policy linkinde yer alan KİŞİSEL VERİLERİN KORUNMASI HAKKINDA BİLGİLENDİRME VE GİZLİLİK POLİTİKASI'na uygun olarak toplamakta, kullanmakta, aktarmakta ve diğer şekillerde işleyebilmektedir. Gizlilik Politikası, işbu Üyelik Sözleşmesi'nin ayrılmaz bir parçasıdır.
4.2. Üye, Hizmetler'den faydalanarak ve/veya bir hesap oluşturarak Gizlilik Politikası'nda belirlendiği şekilde kişisel verilerinin toplanmasına, kullanılmasına, aktarılmasına ve diğer şekillerde işlenmesine açık bir şekilde ve özgür iradesiyle rıza göstermektedir. Kişisel verinin kullanılması ile ilgili koşullar ve bu konudaki haklarınızla ilgili olarak daha fazla bilgi için Gizlilik Politikamızı inceleyebilir ve general@optiyou.com.tr adresine elektronik posta göndererek haklarınızı kullanabilirsiniz.
4.3. Üye tarafından Platform’da beyan edilen ve paylaşılmasına rıza gösterilen kişisel veriler; işbu Üyelik Sözleşmesi ile belirlenen yükümlülüklerin ifası, Platform’un işletilmesi için gereken uygulamaların yürütülmesi, Üye için çeşitli avantajların sağlanıp sunulabilmesi ve Üye’ye özel reklam, satış, pazarlama, anket, benzer amaçlı her türlü elektronik iletişim, profilleme, istatistiksel çalışmalar yapılması amacıyla  ya da iş ortakları tarafından Gizlilik Politikası'na uygun olarak toplanır, saklanır, işlenir, kullanılır ve akdi ilişkilerimize istinaden 3. Kişiler ile paylaşılabilir.
4.4. Üye, kişisel verilerinin bilgilerinin Optiyou Shoes tarafından bu şekilde kullanımına ve saklanmasına rıza gösterdiğini kabul ve beyan eder. Optiyou Shoes söz konusu kişisel verilerin 6698 Sayılı Kişisel Verilerin Korunması Kanunu mad. 12 uyarınca güvenli şekilde saklanması, yetkisiz erişimlerin ve hukuka aykırı veri işlemelerin önlenmesi için gereken her türlü tedbiri alacaktır. Üye kişisel verileri üzerinde 6698 Sayılı Kişisel Verilerin Korunması Kanunu mad. 11 uyarınca sahip olduğu hakları kullanma ve bu verilerinde dilediği zaman değişiklik veya güncelleme yapma hakkına sahiptir.
FİKRİ MÜLKİYET HAKLAR
“Optiyou Shoes” markası ve logosu, “Optiyou Shoes” mobil uygulamasının ve Platform’un tasarımı, yazılımı, alan adı ve bunlara ilişkin olarak KİFİDİS tarafından oluşturulan her türlü marka, tasarım, logo, ticari takdim şekli, slogan ve diğer tüm içeriğin her türlü fikri mülkiyet hakkı ile kendi mülkiyetindedir. Üye, Optiyou Shoes’un veya bağlı şirketlerinin mülkiyetine tabi fikri mülkiyet haklarını yazılı izni olmaksızın kullanamaz, paylaşamaz, dağıtamaz, sergileyemez, çoğaltamaz ve bunlardan türemiş çalışmalar yapamaz. Üye, mobil uygulamasının veya Platform’un bütünü ya da bir kısmını başka bir ortamda Optiyou Shoes’un yazılı izni olmaksızın kullanamaz. Üye'nin, üçüncü kişilerin veya Optiyou Shoes’un fikri mülkiyet haklarını ihlal edecek şekilde davranması halinde, Üye, Optiyou Shoes’un ve/veya söz konusu üçüncü kişinin tüm doğrudan ve dolaylı zararları ile masraflarını tazmin etmekle yükümlüdür.
SÖZLEŞME DEĞİŞİKLİKLER
Optiyou Shoes, tamamen kendi takdirine bağlı olmak üzere, işbu Üyelik Sözleşmesi'ni ve Platform’da yer alan Gizlilik Politikası da dahil her türlü politikayı, hüküm ve şartı uygun göreceği herhangi bir zamanda, yürürlükteki mevzuat hükümlerine aykırı olmamak kaydıyla Platform’da ilan ederek tek taraflı olarak değiştirebilir. İşbu Üyelik Sözleşmesi'nin değişen hükümleri, Platform’da ilan edildikleri tarihte geçerlilik kazanacak, geri kalan hükümler aynen yürürlükte kalarak hüküm ve sonuçlarını doğurmaya devam edecektir.
MÜCBİR SEBEB
Ayaklanma, ambargo, devlet müdahalesi, isyan, işgal, savaş, seferberlik, grev, lokavt, iş eylemleri veya boykotlar dahil olmak üzere işçi-işveren anlaşmazlıkları, siber saldırı, iletişim sorunları, altyapı ve internet arızaları, sisteme ilişkin iyileştirme veya yenileştirme çalışmaları ve bu sebeple meydana gelebilecek arızalar, elektrik kesintisi, yangın, patlama, fırtına, sel, deprem, göç, salgın veya diğer bir doğal felaket veya Optiyou Shoes’un kontrolü dışında gerçekleşen, kusurundan kaynaklanmayan ve makul olarak öngörülemeyecek diğer olaylar ("Mücbir Sebep") Optiyou Shoes’un işbu Üyelik Sözleşmesi'nden doğan yükümlülüklerini ifa etmesini engeller veya geciktirirse, Optiyou Shoes’un ifası Mücbir Sebep sonucunda engellenen veya geciken yükümlülüklerinden dolayı sorumlu tutulamaz ve bu durum işbu Üyelik Sözleşmesi’nin bir ihlali olarak kabul edilemez.
MUHTELİF HÜKÜMLER
8.1. Delil sözleşmesi; Üye, işbu Üyelik Sözleşmesi’nden doğabilecek ihtilaflarda KİFİDİS'ün resmi defter ve ticari kayıtları ile Optiyou Shoes’un veri tabanında, sunucularında tutulan e-arşiv kayıtlarının, elektronik bilgilerin ve bilgisayar kayıtlarının, bağlayıcı, kesin ve münhasır delil teşkil edeceğini ve bu maddenin 6100 sayılı Hukuk Muhakemeleri Kanunu’nun 193. maddesi anlamında delil sözleşmesi niteliğinde olduğunu kabul eder.
8.2. Uygulanacak Hukuk ve Uyuşmazlıkların Çözümü; İşbu Üyelik Sözleşmesi münhasıran Türkiye Cumhuriyeti kanunlarına tabi olacaktır. İşbu Üyelik Sözleşmesi’nden kaynaklanan veya işbu Üyelik Sözleşmesi ile bağlantılı olan her türlü ihtilaf, İstanbul Tüketici Hakem Heyetleri ve İstanbul (Kartal) Mahkemeleri ve İcra Müdürlükleri'nin münhasır yargı yetkisinde olacaktır.
8.3. Bildirim; Optiyou Shoes, Üye ile Üye'nin kayıt olurken bildirmiş olduğu elektronik posta adresi vasıtasıyla veya telefon numarasına arama yapmak ve SMS göndermek suretiyle iletişim kuracaktır. Üye, elektronik posta adresini ve telefon numarasını güncel tutmakla yükümlüdür.
8.4. Üyelik Sözleşmesi'nin Bütünlüğü ve Bölünebilirliği; İşbu Üyelik Sözleşmesi, konuya ilişkin olarak Taraflar arasındaki anlaşmanın tamamını oluşturmaktadır. İşbu Üyelik Sözleşmesi’nin herhangi bir hükmünün yetkili herhangi bir mahkeme, tahkim heyeti veya idari makam tarafından tümüyle veya kısmen geçersiz veya uygulanamaz olduğu veya makul olmadığına karar verilmesi halinde, söz konusu geçersizlik, uygulanamazlık veya makul olmama ölçüsünde işbu Üyelik Sözleşmesi bölünebilir olarak kabul edilecek ve diğer hükümler tümüyle yürürlükte kalmaya devam edecektir.
8.5. Üyelik Sözleşmesi'nin Devri; Üye, Optiyou Shoes’un önceden yazılı onayını almaksızın işbu Üyelik Sözleşmesi’ndeki haklarını veya yükümlülüklerini tümüyle veya kısmen temlik edemeyecektir.
8.6. Tadil ve Feragat; Taraflar'dan birinin Üyelik Sözleşmesi'nde kendisine verilen herhangi bir hakkı kullanmaması ya da icra etmemesi, söz konusu haktan feragat ettiği anlamına gelmeyecek veya söz konusu hakkın daha sonra kullanılmasını ya da icra edilmesini engellemeyecektir.
9 (dokuz) maddeden ibaret işbu Üyelik Sözleşmesi, Üye tarafından her bir hükmü okunarak ve bütünüyle anlaşılarak elektronik ortamda onaylanmak suretiyle, onaylandığı an itibariyle yürürlüğe girmiştir.
*Kişisel verilerimin Optiyou Shoes tarafından doğrudan veya dolaylı pazarlama faaliyetlerinin gerçekleştirilmesi amacıyla işlenmesi suretiyle iletişim bilgilerime; reklam, promosyon, kampanya ve benzeri nitelikte genel ve özel kampanyalar, avantajlar, ürün, hizmet tanıtımları, reklâm, pazar araştırması anketleri ve diğer müşteri memnuniyeti uygulamalarına ilişkin olarak kısa mesaj (SMS), mobil uygulama, anlık bildirim, e-posta v.b. her türlü elektronik iletişim aracı ile ticari elektronik ileti gönderilmesine onay veriyorum ve bu amaçla sınırlı olarak kişisel verilerimin Şirket’in hizmet aldığı üçüncü kişilerle paylaşılmasını, yurt içindeki ve/veya gerekli görüldüğü durumlarda yurt dışındaki veri merkezlerinde de bulundurulabileceğini kabul ediyorum.


''';